name: petit_bibtex
version: 6.1.2

homepage: https://petitparser.github.io
repository: https://github.com/amake/petit_bibtex
description: A BibTeX parser
topics:
  - bibtex

environment:
  sdk: ^3.5.0
dependencies:
  meta: ^1.15.0
  petitparser: ^6.0.0
dev_dependencies:
  http: ^1.2.0
  lints: ^4.0.0
  test: ^1.25.0
