name: petit_bibtex
version: 6.1.0

homepage: https://petitparser.github.io
repository: https://github.com/amake/petit_bibtex
description: A BibTeX parser
topics:
  - bibtex

environment:
  sdk: ^3.5.0
dependencies:
  collection: ^1.19.0
  data: ^0.13.0
  http: ^1.2.0
  meta: ^1.15.0
  more: ^4.3.0
  petitparser: ^6.0.0
  web: ^1.0.0
  xml: ^6.5.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.0
